"""initial migration

Revision ID: 709188b32842
Revises: 
Create Date: 2023-03-12 15:06:02.210506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '709188b32842'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birth_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birth_date')
    # ### end Alembic commands ###
