"""added_postgres

Revision ID: 7c6d0e78b1c9
Revises: 6bb48625929e
Create Date: 2022-10-21 20:05:05.829563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c6d0e78b1c9'
down_revision = '6bb48625929e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
